### ISSUE TITLE
Dein Plugin Manager removes .so files from rplugin/python folder after update of plugins/ :UpdateRemotePlugins

### ISSUE THREAD

**Issue by sandersantema** [raghur/fruzzy#17] opened 2018-12-11 20:58 UTC
The [dein plugin manager](https://github.com/Shougo/dein.vim) removes .so files from .config/dein/.cache/init.vim/.dein/rplugin/python3/ while it doesn't do so with other plugins which install to the same directory. Do you have any idea why this might be? The dein documentation doesn't mention anything about adding the files as a requirement for a plugin.

**Comment by Shougo** [comment] 2018-12-11 23:03
@sandersantema You need to re-build fruzzy binary after update.


```vim
call dein#add('raghur/fruzzy', {'hook_post_update': 'call fruzzy#install()'})
```

vim-plug's configuration does the same thing.

**Comment by Shougo** [comment] 2018-12-11 23:03
And please use the latest version of dein.vim.

**Comment by mhartington** [comment] 2019-01-14 16:15
Seeing similar results, even with the post_update hook. The install function while nice, could be isolated into a standalone install script (bash or python). It would still behave the same way as `install`, but the build command seem to be more reliable

**Comment by Shougo** [comment] 2019-01-14 23:49
@mhartington I don't reproduce the problem.
`post_update` is executed after the directory is merged.
Please check your dein.vim is the latest version.
Please create the new issue in dein.vim with the minimal vimrc and the reproduce instructions.
I will test it later.

**Comment by raghur** [comment] 2019-03-25 04:50
@mhartington, @sandersantema - closing this issue due to inactivity. Feel free to reopen if there's still an issue.

**Closed by raghur** 2019-03-25 04:50 UTC
